name: Deploy application
description: Deploy application with docker image on VPS
author: NikitaLyubimtsev

inputs:
  image_with_tag:
    description: Full image name (e.g. ghcr.io/org/app:{tag})
    required: true
  app_name:
    description: Name of app
    required: true
  host:
    description: url of hosts to deploy
    required: true
  username:
    description: hosts username
    required: true
  key:
    description: hosts ssl key
    required: true
  path:
    description: Path to VPS on docker compose with this app without '~/'
    required: false
    default: ""
  app_type:
    description: Type application (spring, vue)
    required: false
    default: 'spring'
  health_timeout:
    description: Seconds to wait for healthy container
    required: false
    default: "60"
  app_image_url:
    description: URL current docker image
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        script: |
          export APP="${{ inputs.app_name }}"
          export IMAGE="${{ inputs.image_with_tag }}"
          export APP_TYPE="${{ inputs.app_type }}"
          export TIMEOUT="${{ inputs.health_timeout }}"
          export PATH_TO_APP="${{ inputs.path }}"
          export APP_IMAGE_URL="${{ inputs.app_image_url }}"
          bash "$GITHUB_ACTION_PATH/deploy.sh"