name: Publication docker image
description: Publication docker image in Github container registry
author: NikitaLyubimtsev

inputs:
  username:
    description: GitHub username / actor
    required: true
  password:
    description: GitHub password / token
    required: true
  image_repository:
    description: Full GHCR image repository path
    required: true
  default_docker_image:
    description: Tag for docker image without version (latest, beta, dev, dev-sha)
    required: true
  docker_tag_version:
    description: Tag for docker image with last version
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Create branch docker tag
      id: branch-tag
      shell: bash
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}

        if [[ "$BRANCH_NAME" == "main" ]]; then
          TAG="latest"
        else
          SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-')
          TAG="$SAFE_BRANCH"
        fi

        echo "Docker tag: $TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
    - name: Version Docker image pushed
      shell: bash
      run: | 
        set -euo pipefail 
        SOURCE_IMAGE="${{ inputs.default_docker_image }}"
        BRANCH_IMAGE="${{ inputs.image_repository }}:${{ steps.branch-tag.outputs.tag }}"
        docker pull "$SOURCE_IMAGE"
        
        docker tag "$SOURCE_IMAGE" "$BRANCH_IMAGE" 
        docker push "$BRANCH_IMAGE"
        
        if [[ -n "${{ inputs.docker_tag_version }}" ]]; then
          VERSION_IMAGE="${{ inputs.image_repository }}:${{ inputs.docker_tag_version }}"
          docker tag "$SOURCE_IMAGE" "$VERSION_IMAGE"
          docker push "$VERSION_IMAGE"
        fi