name: Build App and Temporary Docker image
description: Build Spring Boot application and Build Docker image with tag associate to branch name
author: NikitaLyubimtsev

inputs:
  image_repository:
    description: Path to docker image repository
    required: true

outputs:
  default_docker_image:
    description: Default docker image tag
    value: ${{ steps.publish-default.outputs.default_image }}

runs:
  using: composite
  steps:
    - name: Gradle cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21
    - name: Build app jar
      shell: bash
      run: ./gradlew clean build -x test
    - name: Create docker default tag
      shell: bash
      id: docker-tag
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-')
        BASE_TAG="ci-${SAFE_BRANCH}"
        TAG="${BASE_TAG}-${GITHUB_SHA:0:7}"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
    - name: Build Docker image (temporary tags)
      shell: bash
      run: docker build -t ${{ inputs.image_repository }}:${{ steps.docker-tag.outputs.tag }} .
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish default docker image
      id: publish-default
      shell: bash
      run: |
        set -euo pipefail
        DEFAULT_DOCKER_IMAGE="${{ inputs.image_repository }}:${{ steps.docker-tag.outputs.tag }}" 
        docker push ${DEFAULT_DOCKER_IMAGE}
        echo "default_image=$DEFAULT_DOCKER_IMAGE" >> $GITHUB_OUTPUT