name: Run Semantic release
author: NikitaLyubimtsev
description: Set default config and run semantic release with current repository

inputs:
  github_token:
    description: GitHub Token
    required: true
outputs:
  last_version:
    description: Last release version with semantic-release
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22
    - name: Install semantic-release deps
      shell: bash
      run: |
        npm init -y
        npm install --no-save \
        semantic-release@25 \
        @semantic-release/commit-analyzer@12 \
        @semantic-release/release-notes-generator@13 \
        @semantic-release/exec@6 \
        @semantic-release/github@12
    - name: Run semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: npx semantic-release --extends "$GITHUB_ACTION_PATH/release.config.js"

    - name: Read new release version
      id: get-version
      shell: bash
      run: |
        VERSION=""
        if [[ -f "$GITHUB_WORKSPACE/.release_version" ]]; then
          VERSION=$(cat .release_version)
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT